### ISSUE TITLE
implement frontend-spa-template

### ISSUE THREAD

**Issue by Kravalg** [VilnaCRM-Org/frontend-spa-template#1]
As a developer, I want to be able to create repositories from the frontend-spa-template.

### Tasks

- [x] use [website repository](https://github.com/VilnaCRM-Org/website) as an example
- [x] init template repository regarding [best practices](https://github.com/alan2207/bulletproof-react)
- [x] Image optimization CI check (https://github.com/marketplace/actions/image-actions)
- [x] add [DI container library](https://github.com/microsoft/tsyringe)
- [x] cache pnpm work for all existing GitHub CI actions

### Subtasks

- [ ] look for IAST tool and see if it can be used it our project
- [x] add artillery for load testing
- [x] add [i18n](https://www.npmjs.com/package/react-i18next) (internationalization)
- [x] add memlab to CI check (https://github.com/facebook/memlab)
- [x] add [web-vitals](https://www.npmjs.com/package/web-vitals) 
- [x] add yaml files linter
- [ ] add auto-updates for repositories that were created from the repository template (@kravalg)

### Optional

- [ ] add https://github.com/artilleryio/artillery-engine-playwright

### Acceptance criteria

- [x] CI works when developer create a PR
- [x] all tests passed
