### ISSUE TITLE
Add autoreleases for the project

### ISSUE THREAD

**Issue by Kravalg** [VilnaCRM-Org/frontend-spa-template#5]
As a developer, I want to be able to don't release the project manually

### Tasks

- [ ] add autorelease CI action
- [ ] add autoprerelease CI action

### Acceptance criteria

- [] CI works when the developer creates a PR
- [] all tests passed
- [] all CI actions works
